# Generated by Django 4.2.30 on 2026-08-10 23:44

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NappePhreatique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_cycle_vie', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise à validation'), ('validee', 'Validée'), ('opposable', 'Opposable'), ('archivee', 'Archivée')], default='brouillon', max_length=20, verbose_name='Statut du cycle de vie')),
                ('millesime', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Millésime (année de référence)')),
                ('source', models.CharField(blank=True, default='', max_length=500, verbose_name='Source des données')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=26192, verbose_name='Géométrie')),
                ('code_nappe', models.CharField(max_length=50, unique=True, verbose_name='Code de la nappe')),
                ('nom_nappe', models.CharField(max_length=255, verbose_name='Nom de la nappe')),
                ('type_nappe', models.CharField(blank=True, default='', max_length=100, verbose_name='Type de nappe (libre/captive)')),
                ('profondeur_moyenne', models.FloatField(blank=True, null=True, verbose_name='Profondeur moyenne (m)')),
                ('debit_exploitation', models.FloatField(blank=True, null=True, verbose_name="Débit d'exploitation (l/s)")),
                ('qualite_eau', models.CharField(blank=True, default='', max_length=100, verbose_name="Qualité de l'eau")),
                ('salinite', models.FloatField(blank=True, null=True, verbose_name='Salinité (g/l)')),
                ('superficie_km2', models.FloatField(blank=True, null=True, verbose_name='Superficie (km²)')),
                ('bassin_hydraulique', models.CharField(blank=True, default='', max_length=255, verbose_name='Bassin hydraulique')),
                ('etat_exploitation', models.CharField(blank=True, default='', max_length=100, verbose_name="État d'exploitation")),
                ('auteur_modification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modifications', to=settings.AUTH_USER_MODEL, verbose_name='Auteur de la dernière modification')),
                ('commune', models.ForeignKey(blank=True, db_column='id_com', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='administration.commune', verbose_name='Commune de rattachement (ID_Com)')),
            ],
            options={
                'verbose_name': 'Nappe phréatique',
                'verbose_name_plural': 'Nappes phréatiques',
                'db_table': 'ressources_eau_nappe_phreatique',
                'ordering': ['code_nappe'],
            },
        ),
        migrations.CreateModel(
            name='Piezometre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_cycle_vie', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise à validation'), ('validee', 'Validée'), ('opposable', 'Opposable'), ('archivee', 'Archivée')], default='brouillon', max_length=20, verbose_name='Statut du cycle de vie')),
                ('millesime', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Millésime (année de référence)')),
                ('source', models.CharField(blank=True, default='', max_length=500, verbose_name='Source des données')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=26192, verbose_name='Géométrie (point)')),
                ('code_piezometre', models.CharField(max_length=50, unique=True, verbose_name='Code du piézomètre')),
                ('nom', models.CharField(blank=True, default='', max_length=255, verbose_name='Nom / localisation')),
                ('altitude_sol', models.FloatField(blank=True, null=True, verbose_name='Altitude du sol (m)')),
                ('profondeur_forage', models.FloatField(blank=True, null=True, verbose_name='Profondeur du forage (m)')),
                ('date_installation', models.DateField(blank=True, null=True, verbose_name="Date d'installation")),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('organisme_gestionnaire', models.CharField(blank=True, default='', max_length=255, verbose_name='Organisme gestionnaire')),
                ('auteur_modification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modifications', to=settings.AUTH_USER_MODEL, verbose_name='Auteur de la dernière modification')),
                ('commune', models.ForeignKey(blank=True, db_column='id_com', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='administration.commune', verbose_name='Commune de rattachement (ID_Com)')),
                ('nappe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piezometres', to='ressources_eau.nappephreatique', verbose_name='Nappe associée')),
            ],
            options={
                'verbose_name': 'Piézomètre',
                'verbose_name_plural': 'Piézomètres',
                'db_table': 'ressources_eau_piezometre',
                'ordering': ['code_piezometre'],
            },
        ),
        migrations.CreateModel(
            name='ReseauHydrographique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_cycle_vie', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise à validation'), ('validee', 'Validée'), ('opposable', 'Opposable'), ('archivee', 'Archivée')], default='brouillon', max_length=20, verbose_name='Statut du cycle de vie')),
                ('millesime', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Millésime (année de référence)')),
                ('source', models.CharField(blank=True, default='', max_length=500, verbose_name='Source des données')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=26192, verbose_name='Géométrie (ligne)')),
                ('code_cours_eau', models.CharField(blank=True, default='', max_length=50, verbose_name="Code du cours d'eau")),
                ('nom_cours_eau', models.CharField(blank=True, default='', max_length=255, verbose_name="Nom du cours d'eau / oued")),
                ('type_cours_eau', models.CharField(blank=True, default='', max_length=100, verbose_name='Type (permanent/temporaire/intermittent)')),
                ('ordre_strahler', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ordre de Strahler')),
                ('longueur_km', models.FloatField(blank=True, null=True, verbose_name='Longueur (km)')),
                ('bassin_versant', models.CharField(blank=True, default='', max_length=255, verbose_name='Bassin versant')),
                ('auteur_modification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modifications', to=settings.AUTH_USER_MODEL, verbose_name='Auteur de la dernière modification')),
                ('commune', models.ForeignKey(blank=True, db_column='id_com', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='administration.commune', verbose_name='Commune de rattachement (ID_Com)')),
            ],
            options={
                'verbose_name': 'Réseau hydrographique',
                'verbose_name_plural': 'Réseaux hydrographiques',
                'db_table': 'ressources_eau_reseau_hydrographique',
                'ordering': ['nom_cours_eau'],
            },
        ),
        migrations.CreateModel(
            name='Barrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_cycle_vie', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise à validation'), ('validee', 'Validée'), ('opposable', 'Opposable'), ('archivee', 'Archivée')], default='brouillon', max_length=20, verbose_name='Statut du cycle de vie')),
                ('millesime', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Millésime (année de référence)')),
                ('source', models.CharField(blank=True, default='', max_length=500, verbose_name='Source des données')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=26192, verbose_name='Géométrie')),
                ('code_barrage', models.CharField(max_length=50, unique=True, verbose_name='Code du barrage')),
                ('nom_barrage', models.CharField(max_length=255, verbose_name='Nom du barrage')),
                ('type_barrage', models.CharField(blank=True, default='', max_length=100, verbose_name='Type de barrage')),
                ('capacite_mm3', models.FloatField(blank=True, null=True, verbose_name='Capacité (Mm³)')),
                ('volume_regularise_mm3', models.FloatField(blank=True, null=True, verbose_name='Volume régularisé (Mm³)')),
                ('cours_eau', models.CharField(blank=True, default='', max_length=255, verbose_name="Cours d'eau / Oued")),
                ('annee_mise_service', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Année de mise en service')),
                ('hauteur_m', models.FloatField(blank=True, null=True, verbose_name='Hauteur de la digue (m)')),
                ('superficie_retenue_ha', models.FloatField(blank=True, null=True, verbose_name='Superficie de la retenue (ha)')),
                ('usage_principal', models.CharField(blank=True, default='', max_length=255, verbose_name='Usage principal (irrigation, AEP, énergie…)')),
                ('auteur_modification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modifications', to=settings.AUTH_USER_MODEL, verbose_name='Auteur de la dernière modification')),
                ('commune', models.ForeignKey(blank=True, db_column='id_com', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='administration.commune', verbose_name='Commune de rattachement (ID_Com)')),
            ],
            options={
                'verbose_name': 'Barrage',
                'verbose_name_plural': 'Barrages',
                'db_table': 'ressources_eau_barrage',
                'ordering': ['nom_barrage'],
            },
        ),
        migrations.CreateModel(
            name='ProfondeurNappe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_releve', models.DateField(verbose_name='Date du relevé')),
                ('profondeur_m', models.FloatField(verbose_name='Profondeur (m)')),
                ('niveau_statique', models.FloatField(blank=True, null=True, verbose_name='Niveau statique (m NGM)')),
                ('niveau_dynamique', models.FloatField(blank=True, null=True, verbose_name='Niveau dynamique (m NGM)')),
                ('methode_mesure', models.CharField(blank=True, default='', max_length=100, verbose_name='Méthode de mesure')),
                ('piezometre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves_profondeur', to='ressources_eau.piezometre', verbose_name='Piézomètre')),
            ],
            options={
                'verbose_name': 'Profondeur de nappe',
                'verbose_name_plural': 'Profondeurs de nappe',
                'db_table': 'ressources_eau_profondeur_nappe',
                'ordering': ['piezometre', '-date_releve'],
                'unique_together': {('piezometre', 'date_releve')},
            },
        ),
    ]
