# Generated by Django 4.2.30 on 2026-08-10 23:44

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneUrbanisable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_cycle_vie', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise à validation'), ('validee', 'Validée'), ('opposable', 'Opposable'), ('archivee', 'Archivée')], default='brouillon', max_length=20, verbose_name='Statut du cycle de vie')),
                ('millesime', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Millésime (année de référence)')),
                ('source', models.CharField(blank=True, default='', max_length=500, verbose_name='Source des données')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=26192, verbose_name='Géométrie')),
                ('code_zone', models.CharField(max_length=50, unique=True, verbose_name='Code de la zone')),
                ('nom_zone', models.CharField(blank=True, default='', max_length=255, verbose_name='Nom de la zone')),
                ('type_document', models.CharField(choices=[('SDAU', 'SDAU'), ('PA', "Plan d'Aménagement"), ('PDAR', 'PDAR'), ('AUTRE', 'Autre')], max_length=20, verbose_name="Type de document d'urbanisme")),
                ('reference_document', models.CharField(blank=True, default='', max_length=255, verbose_name='Référence du document')),
                ('date_homologation', models.DateField(blank=True, null=True, verbose_name="Date d'homologation")),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('superficie_ha', models.FloatField(blank=True, null=True, verbose_name='Superficie (ha)')),
                ('est_en_vigueur', models.BooleanField(default=True, verbose_name='En vigueur')),
                ('organisme_elaboration', models.CharField(blank=True, default='', max_length=255, verbose_name="Organisme d'élaboration")),
                ('vocation_zone', models.CharField(blank=True, default='', help_text='Résidentielle, industrielle, touristique…', max_length=255, verbose_name='Vocation de la zone')),
                ('auteur_modification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modifications', to=settings.AUTH_USER_MODEL, verbose_name='Auteur de la dernière modification')),
                ('commune', models.ForeignKey(blank=True, db_column='id_com', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='administration.commune', verbose_name='Commune de rattachement (ID_Com)')),
            ],
            options={
                'verbose_name': 'Zone urbanisable',
                'verbose_name_plural': 'Zones urbanisables',
                'db_table': 'exclusions_zone_urbanisable',
                'ordering': ['code_zone'],
            },
        ),
        migrations.CreateModel(
            name='StatutFoncier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_cycle_vie', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise à validation'), ('validee', 'Validée'), ('opposable', 'Opposable'), ('archivee', 'Archivée')], default='brouillon', max_length=20, verbose_name='Statut du cycle de vie')),
                ('millesime', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Millésime (année de référence)')),
                ('source', models.CharField(blank=True, default='', max_length=500, verbose_name='Source des données')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=26192, verbose_name='Géométrie')),
                ('code_foncier', models.CharField(max_length=50, unique=True, verbose_name='Code foncier')),
                ('type_statut', models.CharField(choices=[('melk', 'Melk (privé)'), ('collectif', 'Collectif'), ('habous', 'Habous'), ('domanial', 'Domanial'), ('guich', 'Guich'), ('autre', 'Autre')], max_length=50, verbose_name='Type de statut foncier')),
                ('numero_titre', models.CharField(blank=True, default='', max_length=100, verbose_name='Numéro de titre foncier')),
                ('superficie_ha', models.FloatField(blank=True, null=True, verbose_name='Superficie (ha)')),
                ('proprietaire', models.CharField(blank=True, default='', max_length=500, verbose_name='Propriétaire / collectivité')),
                ('date_immatriculation', models.DateField(blank=True, null=True, verbose_name="Date d'immatriculation")),
                ('conservation_fonciere', models.CharField(blank=True, default='', max_length=255, verbose_name='Conservation foncière')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observations')),
                ('auteur_modification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modifications', to=settings.AUTH_USER_MODEL, verbose_name='Auteur de la dernière modification')),
                ('commune', models.ForeignKey(blank=True, db_column='id_com', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='administration.commune', verbose_name='Commune de rattachement (ID_Com)')),
            ],
            options={
                'verbose_name': 'Statut foncier',
                'verbose_name_plural': 'Statuts fonciers',
                'db_table': 'exclusions_statut_foncier',
                'ordering': ['code_foncier'],
            },
        ),
        migrations.CreateModel(
            name='ReseauRoutier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_cycle_vie', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise à validation'), ('validee', 'Validée'), ('opposable', 'Opposable'), ('archivee', 'Archivée')], default='brouillon', max_length=20, verbose_name='Statut du cycle de vie')),
                ('millesime', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Millésime (année de référence)')),
                ('source', models.CharField(blank=True, default='', max_length=500, verbose_name='Source des données')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=26192, verbose_name='Géométrie (ligne)')),
                ('code_route', models.CharField(blank=True, default='', max_length=50, verbose_name='Code de la route')),
                ('nom_route', models.CharField(blank=True, default='', max_length=255, verbose_name='Nom / numéro de la route')),
                ('type_route', models.CharField(blank=True, choices=[('nationale', 'Route nationale'), ('regionale', 'Route régionale'), ('provinciale', 'Route provinciale'), ('communale', 'Route communale'), ('piste', 'Piste'), ('autoroute', 'Autoroute')], default='', max_length=50, verbose_name='Type de route')),
                ('revetement', models.CharField(blank=True, default='', max_length=50, verbose_name='Revêtement (bitumé, terre…)')),
                ('longueur_km', models.FloatField(blank=True, null=True, verbose_name='Longueur (km)')),
                ('largeur_m', models.FloatField(blank=True, null=True, verbose_name='Largeur (m)')),
                ('etat', models.CharField(blank=True, default='', max_length=100, verbose_name='État de la route')),
                ('auteur_modification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modifications', to=settings.AUTH_USER_MODEL, verbose_name='Auteur de la dernière modification')),
                ('commune', models.ForeignKey(blank=True, db_column='id_com', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='administration.commune', verbose_name='Commune de rattachement (ID_Com)')),
            ],
            options={
                'verbose_name': 'Réseau routier',
                'verbose_name_plural': 'Réseau routier',
                'db_table': 'exclusions_reseau_routier',
                'ordering': ['type_route', 'code_route'],
            },
        ),
        migrations.CreateModel(
            name='DomaineForestier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_cycle_vie', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise à validation'), ('validee', 'Validée'), ('opposable', 'Opposable'), ('archivee', 'Archivée')], default='brouillon', max_length=20, verbose_name='Statut du cycle de vie')),
                ('millesime', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Millésime (année de référence)')),
                ('source', models.CharField(blank=True, default='', max_length=500, verbose_name='Source des données')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=26192, verbose_name='Géométrie')),
                ('code_foret', models.CharField(max_length=50, unique=True, verbose_name='Code de la forêt')),
                ('nom_foret', models.CharField(max_length=255, verbose_name='Nom de la forêt')),
                ('type_formation', models.CharField(blank=True, default='', max_length=100, verbose_name='Type de formation (futaie, maquis, steppe…)')),
                ('espece_dominante', models.CharField(blank=True, default='', max_length=255, verbose_name='Espèce dominante')),
                ('superficie_ha', models.FloatField(blank=True, null=True, verbose_name='Superficie (ha)')),
                ('statut_juridique', models.CharField(blank=True, default='', max_length=100, verbose_name='Statut juridique')),
                ('plan_amenagement', models.CharField(blank=True, default='', max_length=255, verbose_name="Plan d'aménagement")),
                ('etat_conservation', models.CharField(blank=True, default='', max_length=100, verbose_name='État de conservation')),
                ('auteur_modification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modifications', to=settings.AUTH_USER_MODEL, verbose_name='Auteur de la dernière modification')),
                ('commune', models.ForeignKey(blank=True, db_column='id_com', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='administration.commune', verbose_name='Commune de rattachement (ID_Com)')),
            ],
            options={
                'verbose_name': 'Domaine forestier',
                'verbose_name_plural': 'Domaines forestiers',
                'db_table': 'exclusions_domaine_forestier',
                'ordering': ['nom_foret'],
            },
        ),
        migrations.CreateModel(
            name='AVNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_cycle_vie', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise à validation'), ('validee', 'Validée'), ('opposable', 'Opposable'), ('archivee', 'Archivée')], default='brouillon', max_length=20, verbose_name='Statut du cycle de vie')),
                ('millesime', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Millésime (année de référence)')),
                ('source', models.CharField(blank=True, default='', max_length=500, verbose_name='Source des données')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=26192, verbose_name='Géométrie')),
                ('code_avna', models.CharField(max_length=50, unique=True, verbose_name='Code AVNA')),
                ('nom', models.CharField(blank=True, default='', max_length=255, verbose_name='Nom / description')),
                ('type_vocation', models.CharField(blank=True, default='', help_text='Industrielle, touristique, militaire, minière…', max_length=255, verbose_name='Type de vocation')),
                ('superficie_ha', models.FloatField(blank=True, null=True, verbose_name='Superficie (ha)')),
                ('reference_juridique', models.CharField(blank=True, default='', max_length=500, verbose_name='Référence juridique')),
                ('date_declaration', models.DateField(blank=True, null=True, verbose_name='Date de déclaration')),
                ('auteur_modification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modifications', to=settings.AUTH_USER_MODEL, verbose_name='Auteur de la dernière modification')),
                ('commune', models.ForeignKey(blank=True, db_column='id_com', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='administration.commune', verbose_name='Commune de rattachement (ID_Com)')),
            ],
            options={
                'verbose_name': 'Zone à vocation non agricole (AVNA)',
                'verbose_name_plural': 'Zones à vocation non agricole (AVNA)',
                'db_table': 'exclusions_avna',
                'ordering': ['code_avna'],
            },
        ),
    ]
