# Generated by Django 4.2.30 on 2026-08-10 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoucheCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_technique', models.CharField(help_text='Format : thematique_objet_millesime (minuscules, sans accents).', max_length=255, unique=True, verbose_name='Nom technique de la couche')),
                ('nom_affichage', models.CharField(max_length=500, verbose_name="Nom d'affichage")),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('thematique', models.CharField(choices=[('administration', 'Limites administratives'), ('geopedologie', 'A. Géopédologie'), ('bioclimat', 'B. Bioclimat'), ('ressources_eau', 'C. Ressources en eau'), ('occupation_agricole', 'D. Occupation agricole'), ('zones_pastorales', 'E. Zones pastorales'), ('exclusions', 'F. Exclusions'), ('classement', 'Classement A/B/C'), ('urbanisme', 'Urbanisme et OCS'), ('foncier', 'Foncier'), ('transverse', 'Socle transverse')], max_length=50, verbose_name='Thématique')),
                ('type_geometrie', models.CharField(choices=[('point', 'Point'), ('ligne', 'Ligne'), ('polygone', 'Polygone'), ('multi_polygone', 'MultiPolygone'), ('raster', 'Raster')], max_length=20, verbose_name='Type de géométrie')),
                ('table_django', models.CharField(blank=True, default='', help_text='app_label.ModelName', max_length=255, verbose_name='Nom de la table/modèle Django')),
                ('srid', models.PositiveIntegerField(default=26192, verbose_name='SRID de stockage')),
                ('est_editable', models.BooleanField(default=False, verbose_name='Éditable par les Éditeurs')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise à validation'), ('validee', 'Validée'), ('opposable', 'Opposable'), ('archivee', 'Archivée')], default='brouillon', max_length=20, verbose_name='Statut du cycle de vie')),
                ('millesime', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Millésime')),
                ('source', models.CharField(blank=True, default='', max_length=500, verbose_name='Source')),
                ('echelle_reference', models.CharField(blank=True, default='', max_length=50, verbose_name='Échelle de référence (ex: 1/25000)')),
                ('forcage_categorie', models.CharField(blank=True, choices=[('A', 'Forçage A'), ('B', 'Forçage B')], help_text='Si renseigné, les unités intersectant cette couche sont automatiquement classées dans cette catégorie.', max_length=1, null=True, verbose_name='Forçage de catégorie (nullable)')),
                ('est_exclusion', models.BooleanField(default=False, help_text='Si coché, les unités intersectant cette couche sont retirées du classement agricole (hors classement).', verbose_name="Couche d'exclusion")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur_modification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couches_modifiees', to=settings.AUTH_USER_MODEL, verbose_name='Dernier auteur')),
            ],
            options={
                'verbose_name': 'Couche du catalogue',
                'verbose_name_plural': 'Couches du catalogue',
                'db_table': 'referentiel_couche_catalogue',
                'ordering': ['thematique', 'nom_technique'],
            },
        ),
        migrations.CreateModel(
            name='MetadonneeISO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500, verbose_name='Titre')),
                ('resume', models.TextField(blank=True, default='', verbose_name='Résumé')),
                ('mots_cles', models.TextField(blank=True, default='', verbose_name='Mots-clés (séparés par des virgules)')),
                ('contact_responsable', models.CharField(blank=True, default='', max_length=255, verbose_name='Contact responsable')),
                ('organisme', models.CharField(blank=True, default='', max_length=255, verbose_name='Organisme producteur')),
                ('date_publication', models.DateField(blank=True, null=True, verbose_name='Date de publication')),
                ('date_revision', models.DateField(blank=True, null=True, verbose_name='Date de révision')),
                ('emprise_ouest', models.FloatField(blank=True, null=True, verbose_name='Emprise Ouest (°)')),
                ('emprise_est', models.FloatField(blank=True, null=True, verbose_name='Emprise Est (°)')),
                ('emprise_nord', models.FloatField(blank=True, null=True, verbose_name='Emprise Nord (°)')),
                ('emprise_sud', models.FloatField(blank=True, null=True, verbose_name='Emprise Sud (°)')),
                ('systeme_reference', models.CharField(default='EPSG:26192', max_length=100, verbose_name='Système de référence')),
                ('qualite', models.TextField(blank=True, default='', verbose_name='Rapport de qualité')),
                ('contraintes_acces', models.TextField(blank=True, default='', verbose_name="Contraintes d'accès")),
                ('licence', models.CharField(blank=True, default='', max_length=255, verbose_name='Licence')),
                ('couche', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadonnee_iso', to='referentiel.couchecatalogue', verbose_name='Couche')),
            ],
            options={
                'verbose_name': 'Métadonnée ISO 19115',
                'verbose_name_plural': 'Métadonnées ISO 19115',
                'db_table': 'referentiel_metadonnee_iso',
            },
        ),
        migrations.CreateModel(
            name='Genealogie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_source', models.CharField(blank=True, default='', max_length=500, verbose_name='Description de la source (si hors catalogue)')),
                ('traitement', models.TextField(blank=True, default='', verbose_name='Description du traitement appliqué')),
                ('parametres', models.JSONField(blank=True, null=True, verbose_name='Paramètres du traitement')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date du traitement')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auteur du traitement')),
                ('couche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genealogies', to='referentiel.couchecatalogue', verbose_name='Couche produite')),
                ('couche_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couches_derivees', to='referentiel.couchecatalogue', verbose_name='Couche source')),
            ],
            options={
                'verbose_name': 'Généalogie',
                'verbose_name_plural': 'Généalogies',
                'db_table': 'referentiel_genealogie',
            },
        ),
        migrations.CreateModel(
            name='DomaineValeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine', models.CharField(db_index=True, help_text='Identifiant du domaine (ex: type_sol, type_geologie).', max_length=100, verbose_name='Nom du domaine')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('libelle', models.CharField(max_length=500, verbose_name='Libellé')),
                ('libelle_ar', models.CharField(blank=True, default='', max_length=500, verbose_name='Libellé (arabe)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Domaine de valeur',
                'verbose_name_plural': 'Domaines de valeurs',
                'db_table': 'referentiel_domaine_valeur',
                'ordering': ['domaine', 'ordre', 'code'],
                'unique_together': {('domaine', 'code')},
            },
        ),
        migrations.CreateModel(
            name='VersionCouche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_version', models.PositiveIntegerField(verbose_name='Numéro de version')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description des modifications')),
                ('statut_avant', models.CharField(blank=True, choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise à validation'), ('validee', 'Validée'), ('opposable', 'Opposable'), ('archivee', 'Archivée')], default='', max_length=20, verbose_name='Statut avant modification')),
                ('statut_apres', models.CharField(blank=True, choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise à validation'), ('validee', 'Validée'), ('opposable', 'Opposable'), ('archivee', 'Archivée')], default='', max_length=20, verbose_name='Statut après modification')),
                ('snapshot_data', models.JSONField(blank=True, null=True, verbose_name='Snapshot des données (pour restauration)')),
                ('date_version', models.DateTimeField(auto_now_add=True, verbose_name='Date de la version')),
                ('est_restaurable', models.BooleanField(default=True, verbose_name='Restaurable')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('couche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='referentiel.couchecatalogue', verbose_name='Couche')),
            ],
            options={
                'verbose_name': 'Version de couche',
                'verbose_name_plural': 'Versions de couches',
                'db_table': 'referentiel_version_couche',
                'ordering': ['-numero_version'],
                'unique_together': {('couche', 'numero_version')},
            },
        ),
    ]
