# Generated by Django 4.2.30 on 2026-08-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couchecatalogue',
            name='thematique',
            field=models.CharField(choices=[('communes', 'Communes'), ('provinces', 'Provinces'), ('regions', 'Régions'), ('car_a', 'Potentiel A (fort)'), ('car_b', 'Potentiel B (moyen)'), ('car_c', 'Potentiel C (faible)'), ('sols', 'Unités pédologiques'), ('oued', 'Oueds et réseau hydrographique'), ('eau_forage', "Points d'eau : Forages"), ('eau_puits', "Points d'eau : Puits"), ('eau_source', "Points d'eau : Sources"), ('gh', 'Périmètres irrigués : GH'), ('pmh', 'Périmètres irrigués : PMH'), ('ppp', 'PPP en irrigation'), ('priv', 'Irrigation privée'), ('nappes', 'Nappes'), ('pei', 'Périmètres PEI'), ('proj_p1', 'Pilier I du PMV'), ('proj_p2', 'Pilier II du PMV'), ('proj_mca', 'Projets MCA'), ('proj_pmvb', 'PMVB'), ('proj_pam', "Sites d'amélioration pastorale"), ('past', 'Zones pastorales'), ('oasis', 'Zones oasiennes'), ('urb', "Documents d'urbanisme"), ('ra', 'Zones RA'), ('ocs', 'Occupation du sol (OCS)'), ('bati', 'Bâti'), ('tf', 'Titres fonciers'), ('stat_melk', 'Statuts fonciers : Melk'), ('stat_coll', 'Statuts fonciers : Collectif'), ('stat_hab', 'Statuts fonciers : Habous'), ('stat_dom', 'Statuts fonciers : Domanial')], max_length=50, verbose_name='Thématique'),
        ),
    ]
