# Generated by Django 4.2.30 on 2026-08-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0002_alter_couchecatalogue_thematique'),
    ]

    operations = [
        migrations.AddField(
            model_name='couchecatalogue',
            name='domaine',
            field=models.CharField(blank=True, default='', help_text="Niveau 1 de l'arborescence (ex: Ressources en eau)", max_length=100, verbose_name='Domaine'),
        ),
        migrations.AddField(
            model_name='couchecatalogue',
            name='sous_domaine',
            field=models.CharField(blank=True, default='', help_text="Niveau 2 de l'arborescence (ex: Eaux souterraines)", max_length=100, verbose_name='Sous-domaine'),
        ),
    ]
