# Generated by Django 4.2.30 on 2026-08-10 23:44

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_cycle_vie', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise à validation'), ('validee', 'Validée'), ('opposable', 'Opposable'), ('archivee', 'Archivée')], default='brouillon', max_length=20, verbose_name='Statut du cycle de vie')),
                ('millesime', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Millésime (année de référence)')),
                ('source', models.CharField(blank=True, default='', max_length=500, verbose_name='Source des données')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('code_province', models.CharField(max_length=10, unique=True, verbose_name='Code province')),
                ('nom_province', models.CharField(max_length=255, verbose_name='Nom de la province')),
                ('nom_province_ar', models.CharField(blank=True, default='', max_length=255, verbose_name='Nom de la province (arabe)')),
                ('chef_lieu', models.CharField(blank=True, default='', max_length=255, verbose_name='Chef-lieu')),
                ('superficie_km2', models.FloatField(blank=True, null=True, verbose_name='Superficie (km²)')),
                ('population', models.PositiveIntegerField(blank=True, null=True, verbose_name='Population')),
                ('annee_recensement', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Année du recensement')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=26192, verbose_name='Géométrie')),
                ('auteur_modification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modifications', to=settings.AUTH_USER_MODEL, verbose_name='Auteur de la dernière modification')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
                'db_table': 'administration_province',
                'ordering': ['nom_province'],
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_cycle_vie', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise à validation'), ('validee', 'Validée'), ('opposable', 'Opposable'), ('archivee', 'Archivée')], default='brouillon', max_length=20, verbose_name='Statut du cycle de vie')),
                ('millesime', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Millésime (année de référence)')),
                ('source', models.CharField(blank=True, default='', max_length=500, verbose_name='Source des données')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('code_commune', models.CharField(max_length=20, unique=True, verbose_name='Code commune')),
                ('nom_commune', models.CharField(max_length=255, verbose_name='Nom de la commune')),
                ('nom_commune_ar', models.CharField(blank=True, default='', max_length=255, verbose_name='Nom de la commune (arabe)')),
                ('type_commune', models.CharField(blank=True, default='', max_length=50, verbose_name='Type (urbaine/rurale)')),
                ('superficie_km2', models.FloatField(blank=True, null=True, verbose_name='Superficie (km²)')),
                ('population', models.PositiveIntegerField(blank=True, null=True, verbose_name='Population')),
                ('annee_recensement', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Année du recensement')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=26192, verbose_name='Géométrie')),
                ('auteur_modification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modifications', to=settings.AUTH_USER_MODEL, verbose_name='Auteur de la dernière modification')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='administration.province', verbose_name='Province')),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
                'db_table': 'administration_commune',
                'ordering': ['nom_commune'],
            },
        ),
    ]
