# Generated by Django 4.2.30 on 2026-08-10 23:44

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StationClimatique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_cycle_vie', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise à validation'), ('validee', 'Validée'), ('opposable', 'Opposable'), ('archivee', 'Archivée')], default='brouillon', max_length=20, verbose_name='Statut du cycle de vie')),
                ('millesime', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Millésime (année de référence)')),
                ('source', models.CharField(blank=True, default='', max_length=500, verbose_name='Source des données')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=26192, verbose_name='Géométrie (point)')),
                ('code_station', models.CharField(max_length=50, unique=True, verbose_name='Code de la station')),
                ('nom_station', models.CharField(max_length=255, verbose_name='Nom de la station')),
                ('altitude', models.FloatField(blank=True, null=True, verbose_name='Altitude (m)')),
                ('organisme_gestionnaire', models.CharField(blank=True, default='', max_length=255, verbose_name='Organisme gestionnaire')),
                ('date_mise_en_service', models.DateField(blank=True, null=True, verbose_name='Date de mise en service')),
                ('est_active', models.BooleanField(default=True, verbose_name='Station active')),
                ('auteur_modification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modifications', to=settings.AUTH_USER_MODEL, verbose_name='Auteur de la dernière modification')),
                ('commune', models.ForeignKey(blank=True, db_column='id_com', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='administration.commune', verbose_name='Commune de rattachement (ID_Com)')),
            ],
            options={
                'verbose_name': 'Station climatique',
                'verbose_name_plural': 'Stations climatiques',
                'db_table': 'bioclimat_station_climatique',
                'ordering': ['code_station'],
            },
        ),
        migrations.CreateModel(
            name='EtageBioclimatique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_cycle_vie', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise à validation'), ('validee', 'Validée'), ('opposable', 'Opposable'), ('archivee', 'Archivée')], default='brouillon', max_length=20, verbose_name='Statut du cycle de vie')),
                ('millesime', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Millésime (année de référence)')),
                ('source', models.CharField(blank=True, default='', max_length=500, verbose_name='Source des données')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=26192, verbose_name='Géométrie')),
                ('code_etage', models.CharField(max_length=50, unique=True, verbose_name="Code de l'étage bioclimatique")),
                ('nom_etage', models.CharField(max_length=255, verbose_name="Nom de l'étage bioclimatique")),
                ('type_climat', models.CharField(blank=True, default='', max_length=100, verbose_name='Type de climat')),
                ('precipitation_annuelle_min', models.FloatField(blank=True, null=True, verbose_name='Précipitation annuelle min (mm)')),
                ('precipitation_annuelle_max', models.FloatField(blank=True, null=True, verbose_name='Précipitation annuelle max (mm)')),
                ('temperature_moyenne_min', models.FloatField(blank=True, null=True, verbose_name='Température moyenne min (°C)')),
                ('temperature_moyenne_max', models.FloatField(blank=True, null=True, verbose_name='Température moyenne max (°C)')),
                ('indice_aridite', models.FloatField(blank=True, null=True, verbose_name="Indice d'aridité")),
                ('quotient_emberger', models.FloatField(blank=True, null=True, verbose_name="Quotient d'Emberger (Q2)")),
                ('superficie_ha', models.FloatField(blank=True, null=True, verbose_name='Superficie (ha)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('auteur_modification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modifications', to=settings.AUTH_USER_MODEL, verbose_name='Auteur de la dernière modification')),
                ('commune', models.ForeignKey(blank=True, db_column='id_com', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='administration.commune', verbose_name='Commune de rattachement (ID_Com)')),
            ],
            options={
                'verbose_name': 'Étage bioclimatique',
                'verbose_name_plural': 'Étages bioclimatiques',
                'db_table': 'bioclimat_etage_bioclimatique',
                'ordering': ['code_etage'],
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveSmallIntegerField(verbose_name='Année')),
                ('mois', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mois (1-12, null = annuel)')),
                ('temperature_moyenne', models.FloatField(verbose_name='Température moyenne (°C)')),
                ('temperature_min', models.FloatField(blank=True, null=True, verbose_name='Température minimale (°C)')),
                ('temperature_max', models.FloatField(blank=True, null=True, verbose_name='Température maximale (°C)')),
                ('amplitude_thermique', models.FloatField(blank=True, null=True, verbose_name='Amplitude thermique (°C)')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperatures', to='bioclimat.stationclimatique', verbose_name='Station')),
            ],
            options={
                'verbose_name': 'Température',
                'verbose_name_plural': 'Températures',
                'db_table': 'bioclimat_temperature',
                'ordering': ['station', '-annee', 'mois'],
                'unique_together': {('station', 'annee', 'mois')},
            },
        ),
        migrations.CreateModel(
            name='Precipitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveSmallIntegerField(verbose_name='Année')),
                ('mois', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mois (1-12, null = annuel)')),
                ('precipitation_mm', models.FloatField(verbose_name='Précipitation (mm)')),
                ('nombre_jours_pluie', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nombre de jours de pluie')),
                ('precipitation_max_24h', models.FloatField(blank=True, null=True, verbose_name='Précipitation max en 24h (mm)')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precipitations', to='bioclimat.stationclimatique', verbose_name='Station')),
            ],
            options={
                'verbose_name': 'Précipitation',
                'verbose_name_plural': 'Précipitations',
                'db_table': 'bioclimat_precipitation',
                'ordering': ['station', '-annee', 'mois'],
                'unique_together': {('station', 'annee', 'mois')},
            },
        ),
    ]
