# Generated by Django 4.2.30 on 2026-08-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitecarteagricole',
            name='score_clim',
            field=models.FloatField(blank=True, default=0.5, help_text='Aptitude climatique, normalisé 0-1.', null=True, verbose_name='Score climat (0-1)'),
        ),
        migrations.AddField(
            model_name='unitecarteagricole',
            name='score_cont',
            field=models.FloatField(blank=True, default=0.5, help_text='Contraintes physiques (pente, érosion), normalisé 0-1.', null=True, verbose_name='Score contraintes (0-1)'),
        ),
        migrations.AddField(
            model_name='unitecarteagricole',
            name='score_eau',
            field=models.FloatField(blank=True, default=0.5, help_text='Proximité aux ressources en eau, normalisé 0-1.', null=True, verbose_name='Score eau (0-1)'),
        ),
        migrations.AddField(
            model_name='unitecarteagricole',
            name='score_occ',
            field=models.FloatField(blank=True, default=0.5, help_text='Occupation du sol actuelle, normalisé 0-1.', null=True, verbose_name='Score occupation du sol (0-1)'),
        ),
        migrations.AddField(
            model_name='unitecarteagricole',
            name='score_sol',
            field=models.FloatField(blank=True, default=0.5, help_text='Qualité pédologique, normalisé 0-1.', null=True, verbose_name='Score sol (0-1)'),
        ),
        migrations.AlterField(
            model_name='unitecarteagricole',
            name='est_car_validee',
            field=models.BooleanField(default=False, verbose_name='Fait partie de la CAR validée (référentiel opposable)'),
        ),
    ]
