# Generated by Django 4.2.30 on 2026-08-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='couches_editables',
            field=models.JSONField(blank=True, help_text='Liste des IDs de couches que cet utilisateur peut éditer. Null = toutes les couches éditables selon le rôle.', null=True, verbose_name='Couches éditables (IDs)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fonction',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Fonction'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='modules_autorises',
            field=models.JSONField(blank=True, help_text='Liste des codes modules accessibles. Null = tous selon le rôle.', null=True, verbose_name='Modules autorisés'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organisme',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Organisme de rattachement'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferences',
            field=models.JSONField(blank=True, null=True, verbose_name="Préférences d'interface (JSON)"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('consult', 'Consultation'), ('decideur', 'Décideur'), ('editeur', 'Éditeur'), ('admin', 'Administrateur SIG')], default='consult', max_length=20, verbose_name='Profil / rôle'),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='users_customuser',
        ),
    ]
