# Generated by Django 4.2.30 on 2026-08-10 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_utilisateur', models.CharField(blank=True, default='', max_length=20, verbose_name="Rôle au moment de l'action")),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('validate', 'Validation'), ('publish', 'Publication (opposable)'), ('archive', 'Archivage'), ('restore', 'Restauration'), ('calcul', 'Calcul AMC/AHP'), ('forcage', 'Application de forçage'), ('exclusion', "Application d'exclusion"), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('export', 'Export'), ('import', 'Import')], max_length=20, verbose_name="Type d'action")),
                ('module', models.CharField(blank=True, default='', max_length=50, verbose_name='Module concerné (M1-M13)')),
                ('app_label', models.CharField(blank=True, default='', max_length=100, verbose_name='App Django')),
                ('model_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Modèle Django')),
                ('object_id', models.CharField(blank=True, default='', max_length=100, verbose_name="ID de l'objet")),
                ('object_repr', models.CharField(blank=True, default='', max_length=500, verbose_name="Représentation de l'objet")),
                ('champ_modifie', models.CharField(blank=True, default='', max_length=255, verbose_name='Champ modifié')),
                ('valeur_avant', models.TextField(blank=True, default='', verbose_name='Valeur avant modification')),
                ('valeur_apres', models.TextField(blank=True, default='', verbose_name='Valeur après modification')),
                ('donnees_completes', models.JSONField(blank=True, null=True, verbose_name='Données complètes (snapshot JSON)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description / justification')),
                ('regle_declenchee', models.CharField(blank=True, default='', help_text='Ex: forcage:PMH, exclusion:Zone_Urbanisable', max_length=255, verbose_name='Règle déclenchée (si applicable)')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('date_action', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Date de l'action")),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Entrée d'audit",
                'verbose_name_plural': "Journal d'audit",
                'db_table': 'audit_log',
                'ordering': ['-date_action'],
                'indexes': [models.Index(fields=['app_label', 'model_name', 'object_id'], name='audit_log_app_lab_5e6a03_idx'), models.Index(fields=['utilisateur', 'date_action'], name='audit_log_utilisa_f2e494_idx'), models.Index(fields=['action', 'date_action'], name='audit_log_action_0450b1_idx')],
            },
        ),
    ]
