# Generated by Django 4.2.30 on 2026-08-07 08:20

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoucheCartographique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True, verbose_name='Nom de la couche')),
                ('description', models.TextField(blank=True, null=True)),
                ('est_editable_par_editeur', models.BooleanField(default=False, verbose_name='Éditable par les Éditeurs')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioCAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du Scénario')),
                ('criteres', models.JSONField(blank=True, null=True, verbose_name='Critères')),
                ('poids', models.JSONField(blank=True, null=True, verbose_name='Poids (AMC/AHP)')),
                ('seuils', models.JSONField(blank=True, null=True, verbose_name='Seuils')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_valide', models.BooleanField(default=False, verbose_name='Est la CAR validée (référentiel opposable)')),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Géométrie')),
                ('categorie_car', models.CharField(blank=True, max_length=50, null=True, verbose_name='Catégorie CAR (A/B/C)')),
                ('type_sol', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type de sol')),
                ('nappe', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nappe phréatique')),
                ('scenario_car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelles', to='geodata.scenariocar')),
            ],
        ),
    ]
