# Generated by Django 4.2.30 on 2026-08-10 23:44

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonePastorale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_cycle_vie', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise à validation'), ('validee', 'Validée'), ('opposable', 'Opposable'), ('archivee', 'Archivée')], default='brouillon', max_length=20, verbose_name='Statut du cycle de vie')),
                ('millesime', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Millésime (année de référence)')),
                ('source', models.CharField(blank=True, default='', max_length=500, verbose_name='Source des données')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=26192, verbose_name='Géométrie')),
                ('code_zone', models.CharField(max_length=50, unique=True, verbose_name='Code de la zone pastorale')),
                ('nom_zone', models.CharField(max_length=255, verbose_name='Nom de la zone')),
                ('type_parcours', models.CharField(blank=True, default='', max_length=100, verbose_name='Type de parcours')),
                ('superficie_ha', models.FloatField(blank=True, null=True, verbose_name='Superficie (ha)')),
                ('especes_dominantes', models.TextField(blank=True, default='', verbose_name='Espèces dominantes')),
                ('charge_animale', models.FloatField(blank=True, null=True, verbose_name='Charge animale (UPB/ha)')),
                ('etat_degradation', models.CharField(blank=True, default='', max_length=100, verbose_name='État de dégradation')),
                ('type_sol', models.CharField(blank=True, default='', max_length=255, verbose_name='Type de sol')),
                ('pluviometrie_moyenne', models.FloatField(blank=True, null=True, verbose_name='Pluviométrie moyenne (mm/an)')),
                ('tribu_usage', models.CharField(blank=True, default='', max_length=255, verbose_name="Tribu / groupe d'usage")),
                ('auteur_modification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modifications', to=settings.AUTH_USER_MODEL, verbose_name='Auteur de la dernière modification')),
                ('commune', models.ForeignKey(blank=True, db_column='id_com', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='administration.commune', verbose_name='Commune de rattachement (ID_Com)')),
            ],
            options={
                'verbose_name': 'Zone pastorale',
                'verbose_name_plural': 'Zones pastorales',
                'db_table': 'zones_pastorales_zone_pastorale',
                'ordering': ['code_zone'],
            },
        ),
        migrations.CreateModel(
            name='SiteAmeliorationPastorale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_cycle_vie', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise à validation'), ('validee', 'Validée'), ('opposable', 'Opposable'), ('archivee', 'Archivée')], default='brouillon', max_length=20, verbose_name='Statut du cycle de vie')),
                ('millesime', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Millésime (année de référence)')),
                ('source', models.CharField(blank=True, default='', max_length=500, verbose_name='Source des données')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=26192, verbose_name='Géométrie')),
                ('code_site', models.CharField(max_length=50, unique=True, verbose_name='Code du site')),
                ('nom_site', models.CharField(max_length=255, verbose_name='Nom du site')),
                ('type_amelioration', models.CharField(blank=True, default='', help_text='Ensemencement, mise en défens, plantation arbustive…', max_length=255, verbose_name="Type d'amélioration")),
                ('superficie_ha', models.FloatField(blank=True, null=True, verbose_name='Superficie (ha)')),
                ('annee_realisation', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Année de réalisation')),
                ('especes_introduites', models.TextField(blank=True, default='', verbose_name='Espèces introduites')),
                ('maitre_ouvrage', models.CharField(blank=True, default='', max_length=255, verbose_name="Maître d'ouvrage")),
                ('cout_investissement', models.FloatField(blank=True, null=True, verbose_name="Coût d'investissement (MDH)")),
                ('etat_site', models.CharField(blank=True, default='', max_length=100, verbose_name='État du site')),
                ('nombre_beneficiaires', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de bénéficiaires')),
                ('auteur_modification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modifications', to=settings.AUTH_USER_MODEL, verbose_name='Auteur de la dernière modification')),
                ('commune', models.ForeignKey(blank=True, db_column='id_com', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='administration.commune', verbose_name='Commune de rattachement (ID_Com)')),
                ('zone_pastorale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites_amelioration', to='zones_pastorales.zonepastorale', verbose_name='Zone pastorale parente')),
            ],
            options={
                'verbose_name': "Site d'amélioration pastorale",
                'verbose_name_plural': "Sites d'amélioration pastorale",
                'db_table': 'zones_pastorales_site_amelioration',
                'ordering': ['code_site'],
            },
        ),
    ]
